### ISSUE TITLE
Path is sometimes converted to match wrong pattern

### ISSUE THREAD

**Issue by sudishth** [lauriii/subpathauto#3]
'/node/123' has alias '/about-me' which makes about-me/edit and about-me/delete paths work.

If there's path '/about-me/something-else', but '/node/123/something-else' doesn't exist, we shouldn't convert the path to '/node/123/something-else'.

**Comment by lauriii** [comment]
I have moved to use Drupal.org as a platform to host this module. This issue has been moved to Drupal.org and can be found here: https://www.drupal.org/node/2792325
